#!/bin/bash

#
# Configuration file for default serial CPU tests
#

#-------------------------------------------------------------------------------
# Branches 
#
branch="master"
regtests_branch="master"

#-------------------------------------------------------------------------------
# Architecture
#
architecture="cpu-openmp"

#-------------------------------------------------------------------------------
# CMake args
#
cmake_args+=("-DBUILD_TYPE=Debug")
cmake_args+=("-DPLATFORMS=OPENMP")
cmake_args+=("-DOPALX_ENABLE_UNIT_TESTS=ON")
cmake_args+=("-DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm@21/bin/clang")
cmake_args+=("-DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm@21/bin/clang++")
cmake_args+=("-DMPI_C_COMPILER=/opt/homebrew/Cellar/open-mpi/5.0.8/bin/mpicc")
cmake_args+=("-DMPI_CXX_COMPILER=/opt/homebrew/Cellar/open-mpi/5.0.8/bin/mpicxx")
cmake_args+=("-DOpenMP_ROOT=/opt/homebrew/opt/libomp")
cmake_args+=("-DOpenMP_C_FLAGS=-fopenmp=libomp")
cmake_args+=("-DOpenMP_CXX_FLAGS=-fopenmp=libomp")
cmake_args+=("-DOpenMP_C_INCLUDE_DIR=/opt/homebrew/opt/libomp/include")
cmake_args+=("-DOpenMP_CXX_INCLUDE_DIR=/opt/homebrew/opt/libomp/include")
cmake_args+=("-DOpenMP_libomp_LIBRARY=/opt/homebrew/opt/libomp/lib/libomp.dylib")

#-------------------------------------------------------------------------------
# OPALX args 
#
#opalx_args=()

#-------------------------------------------------------------------------------
# Unit tests: set to 'yes' to run ctest -L unit after build
#
do_unittests='yes'
#unittests_args=()

#-------------------------------------------------------------------------------
# Modules 
#
#module purge
