#!/usr/bin/env bash

#
# Compile OPALX and run unit- and regression tests.
#

# exit on error
set -o errexit

declare -ri	EC_ARG_ERROR=1
declare -ri	EC_GIT_ERROR=10

declare branch="master"
declare branch_slug="master"
declare regtests_branch="master"
declare architecture="cpu-serial"

# indexed arrays
declare -a cmake_args=()
declare -a opalx_args=()
declare -a unittests_args=()

declare -r today=$(date +%Y-%m-%d)
declare -r time=$(date +%H-%M)
declare -r timestamp="${today}_${time}"

#------------------------------------------------------------------------------- 
# error handling
#
declare aborting='yes'

# SITINT or SIGTERM event calls _signal_handler
# exits the script with the errorcode 
trap _signal_handler SIGINT SIGTERM
_signal_handler() {
	local ec=$?
	echo "Aborting ..."
	aborting='yes'
	exit ${ec}
}

# EXIT event calls _exit
# if in aborting state exit the script with the errorcode 
trap _exit EXIT
_exit() {
        local -i ec=$?
	if [[ ${aborting} == 'yes' ]]; then
		return ${ec}
	fi
    if [[ "${overview_dirty}" == 'yes' ]]; then
	    update_overview
    fi
}

# if errorcode ($1) > 0, then redirect output to 
# stderr and exit the script with the errorcode
die() {
	(( $1 > 0 )) && exec 1>&2
	echo -e "$2\n"
	exit $1
}

usage() {
	echo "Usage:
	$(basename "$0") [OPTIONS...] 

Compile OPALX, run regression-tests. 
On the first time this script is called, the following steps will be
performed:

1. clone OPALX repository
2. compile OPALX, stop on error
3. clone regression-tests repository
4. run regression-tests

On further calls:

1. update OPAL repository
2. compile OPAL only if changed, stop on error
3. update regression-tests repository
4. run regression-tests only if OPAL has been compiled or the some 
    regression-tests has been changed.


OPTIONS:
===========
--publish-dir=DIR
	Prefix of the publication directory. If not set
	or empty, no HTML output will be created.

--config=FILE
	The options above can be defined in the configuration FILE.
	Configuration files can also set the default 'branch',
	'regtests_branch', and 'architecture' variables
	(e.g., cpu-serial, cpu-openmp, gpu-cuda-a100) to organize
	builds and results by architecture.

--opalx-branch=BRANCH
	Override the OPALX branch to check out. If not set, the
	configuration file default is used.

--branches-file=FILE
	Read OPALX branches to build and test from FILE. When this option
	is not set, ${HOME}/branches.txt is used if it exists. Empty lines
	and lines starting with '#' are ignored. --opalx-branch overrides
	this batch mode.

--opalx-exe-path=DIR
	Use an existing OPALX executable directory instead of updating and
	compiling the managed workspace checkout.

--opalx-build-dir=DIR
	Use an existing OPALX build directory for unit tests and derive the
	executable from DIR/src/opalx unless --opalx-exe-path is also set.

--regtests-branch=BRANCH
	Override the regression-tests branch to check out. If not set,
	the configuration file default is used.
	
--compile
	Compile OPAL even nothing changed and a binary exists.

--no-clean-after-compile
	Keep object files after a successful compile. By default the build
	tree is cleaned after compilation to save storage while preserving
	the compiled executable and configured build tree.

--unit-tests
	Run unit-tests even OPAL has not been compiled.

--no-unit-tests
	Do not run unit tests, overriding the configuration file default.

--reg-tests
	Run regression-tests even OPAL has not been compiled and the
	tests has not been changed.

--test[=NAME]
	Run one regression test only. Without NAME, run Spin-Tracking.

--no-reg-tests
	Do not run regression tests, overriding the configuration file default.

--run-local-now
	Skip update/build/run and only generate comparison plots for the
	local regression test in the current directory.

--no-gpl
	Use Python plotting instead of gnuplot for regression comparison
	plots.

--only-generate-web-page
	Write a local plot-summary.html page in each regression test
	directory after plot generation. If this is the only action flag,
	run in local compare-only mode without update/build/run and also
	generate the standard regression results HTML/XML page locally.

-f | --force
	Force compiling OPAL and run unit- and regression-tests.

-h | -? | --help
	This help.

" 1>&2
	exit 1
}

#-------------------------------------------------------------------------------
# handle arguments
#

# default URL for OPALX source and regression-tests repository
declare src_repo_url="https://github.com/OPALX-project/OPALX.git"
declare	tests_repo_url="https://github.com/OPALX-project/regression-tests-x.git"

# absolute or relative directory where to publish the results
# of the regression und unit tests. If empty, nothing will be
# published.
declare -x	publish_dir=''

# run unit- and/or regression tests
declare	opt_force='no'
declare	do_compile='no'
declare do_unittests='no'
declare do_regtests='no'
declare do_run_local_now='no'
declare do_no_gpl='no'
declare do_generate_web_page='no'
declare clean_after_compile='yes'
declare explicit_actions='no'

# configuration file
declare	opt_config_file="default-${branch}.conf"
declare opt_opalx_branch=""
declare opt_branches_file=""
declare opt_branches_file_set='no'
declare opt_regtests_branch=""
declare opt_opalx_exe_path=""
declare opt_opalx_build_dir=""
declare opt_single_regtest=""
declare managed_build_layout='yes'

# tests to run, all if non passed as argument
declare -a tests=()

while (( $# > 0 )); do
	case $1 in
        --config|--config=* )
            if [[ $1 == *=* ]]; then
                opt_config_file="${1#*=}"
            else
                opt_config_file="$2"; shift 1
            fi
            if [[ ! -e "${opt_config_file}" ]]; then
                die 1 "ERROR: configuration file does not exist - ${opt_config_file}"
            fi
            source "${opt_config_file}"
            if (( $? != 0)); then
                die 1 "ERROR: cannot source configuration file - ${opt_config_file} "
            fi
            ;;
		--publish-dir|--publish-dir=* )
             
            if [[ $1 == *=* ]]; then
                publish_dir="${1#*=}"
            else
                publish_dir="$2"; shift 1
            fi
            if [[ -n ${publish_dir} ]]; then
                publish_dir=$(python3 -c "import os, sys; print(os.path.abspath(sys.argv[1]))" "${publish_dir}")
            fi
            ;;
        --opalx-branch|--opalx-branch=* )
            if [[ $1 == *=* ]]; then
                opt_opalx_branch="${1#*=}"
            else
                opt_opalx_branch="$2"; shift 1
            fi
            ;;
        --branches-file|--branches-file=* )
            opt_branches_file_set='yes'
            if [[ $1 == *=* ]]; then
                opt_branches_file="${1#*=}"
            else
                opt_branches_file="$2"; shift 1
            fi
            ;;
        --opalx-exe-path|--opalx-exe-path=* )
            if [[ $1 == *=* ]]; then
                opt_opalx_exe_path="${1#*=}"
            else
                opt_opalx_exe_path="$2"; shift 1
            fi
            ;;
        --opalx-build-dir|--opalx-build-dir=* )
            if [[ $1 == *=* ]]; then
                opt_opalx_build_dir="${1#*=}"
            else
                opt_opalx_build_dir="$2"; shift 1
            fi
            ;;
        --regtests-branch|--regtests-branch=* )
            if [[ $1 == *=* ]]; then
                opt_regtests_branch="${1#*=}"
            else
                opt_regtests_branch="$2"; shift 1
            fi
            ;;
		--compile )
            explicit_actions='yes'
			do_compile='yes'
			;;
        --no-clean-after-compile )
            clean_after_compile='no'
            ;;
        --reg-tests )
            explicit_actions='yes'
            do_regtests='yes'
            ;;
        --test|--test=* )
            explicit_actions='yes'
            do_regtests='yes'
            if [[ $1 == *=* ]]; then
                opt_single_regtest="${1#*=}"
            else
                opt_single_regtest="Spin-Tracking"
            fi
            ;;
        --no-reg-tests )
            explicit_actions='yes'
            do_regtests='no'
            ;;
        --run-local-now )
            explicit_actions='yes'
            do_run_local_now='yes'
            ;;
        --no-gpl )
            do_no_gpl='yes'
            ;;
        --only-generate-web-page )
            explicit_actions='yes'
            do_generate_web_page='yes'
            ;;
        --unit-tests )
            explicit_actions='yes'
            do_unittests='yes'
			;;
        --no-unit-tests )
            explicit_actions='yes'
            do_unittests='no'
			;;
		-f | --force )
            explicit_actions='yes'
		    opt_force='yes'
			do_compile='yes'
            do_regtests='yes'
            do_unittests='yes'
		    ;;
		-h | -\? | --help )
			usage
			;;
		-* )
            echo "Unknown option: $1" 1>&2
            exit
            ;;
		* )
            tests+=( "$1" )
            ;;
	esac
	shift 1
done

if [[ -n "${opt_opalx_branch}" ]]; then
    branch="${opt_opalx_branch}"
fi

if [[ -n "${opt_regtests_branch}" ]]; then
    regtests_branch="${opt_regtests_branch}"
fi

if [[ -n "${opt_single_regtest}" ]]; then
    tests=( "${opt_single_regtest}" )
fi

if [[ -n "${publish_dir}" ]]; then
    mkdir -p "${publish_dir}"
fi

# Ensure unit tests are enabled for nightly builds unless explicitly set in config (match NightlyBuildX).
case " ${cmake_args[*]} " in
    *"OPALX_ENABLE_UNIT_TESTS"*)
        ;;
    *)
        cmake_args+=("-DOPALX_ENABLE_UNIT_TESTS=ON")
        ;;
esac

#-------------------------------------------------------------------------------
# Directory layout
#
# ${PREFIX}/scripts					                        ${bindir}
# ${PREFIX}/workspace					                    ${workspace}
# ${PREFIX}/workspace/opalx				                    ${srcdir}
# ${PREFIX}/workspace/build/${architecture}/build-${branch_slug} ${builddir}
# ${PREFIX}/workspace/regression-tests-x			            ${testsbase}
# ${PREFIX}/workspace/regression-tests-x/RegressionTests	    ${testsdir}

# Get absolute path to this script, portable handling for macOS/Linux
if [[ "$(uname)" == "Darwin" ]]; then
    declare -r abs_scriptname=$(python3 -c "import os, sys; print(os.path.abspath(sys.argv[1]))" "$0")
else
    declare -r abs_scriptname=$(readlink -f "$0")
fi

declare -r bindir="${abs_scriptname%/*}"
declare -r prefix="${bindir%/*}"
declare -r workspace="${prefix}/workspace"
declare -r srcdir="${workspace}/opalx"
declare    builddir=""
declare    opalx_exe_path="${builddir}/src"
declare -r testsbase="${workspace}/regression-tests-x"
declare -r testsdir="${testsbase}/RegressionTests"
declare    overview_dirty='no'

# Result variables
result_compile="-"

# Unit tests
result_u_total="-"
result_u_passed="-"
result_u_failed="-"
result_u_disabled="-"
result_u_broken="-"

# Regression tests
result_r_total="-"
result_r_passed="-"
result_r_failed="-"
result_r_disabled="-"
result_r_broken="-"

sanitize_path_component() {
    local value="$1"
    value="${value//\//_}"
    value="${value// /_}"
    value="${value//[^A-Za-z0-9._-]/_}"
    [[ -n "${value}" ]] || value="default"
    printf "%s" "${value}"
}

escape_sed_replacement() {
    printf "%s" "$1" | sed 's/[\/&]/\\&/g'
}

set_branch_context() {
    branch_slug=$(sanitize_path_component "${branch}")
    if [[ "${managed_build_layout}" == 'yes' ]]; then
        builddir="${workspace}/build/${architecture}/build-${branch_slug}"
        opalx_exe_path="${builddir}/src"
    fi
}

reset_results() {
    result_compile="-"
    result_u_total="-"
    result_u_passed="-"
    result_u_failed="-"
    result_u_disabled="-"
    result_u_broken="-"
    result_r_total="-"
    result_r_passed="-"
    result_r_failed="-"
    result_r_disabled="-"
    result_r_broken="-"
}

read_branches_file() {
    local -r file="$1"
    [[ -f "${file}" ]] || die ${EC_ARG_ERROR} "ERROR: branches file does not exist - ${file}"

    local line
    while IFS= read -r line || [[ -n "${line}" ]]; do
        line="${line%%#*}"
        line="${line#"${line%%[![:space:]]*}"}"
        line="${line%"${line##*[![:space:]]}"}"
        [[ -n "${line}" ]] || continue
        branches+=( "${line}" )
    done < "${file}"

    (( ${#branches[@]} > 0 )) || die ${EC_ARG_ERROR} "ERROR: branches file is empty - ${file}"
}

restore_opalx_source_overrides() {
    [[ "${PWD}" == "${srcdir}" ]] || return 0
    [[ -f "src/PartBunch/FieldMirror.hpp" ]] || return 0

    if ! git diff --quiet -- "src/PartBunch/FieldMirror.hpp"; then
        git checkout -- "src/PartBunch/FieldMirror.hpp"
        echo "Restored generated FieldMirror.hpp override before branch checkout."
    fi
}

checkout_requested_ref() {
    local -r _branch="$1"
    local pr_number=""

    git fetch --prune origin

    if git show-ref --verify --quiet "refs/heads/${_branch}"; then
        git checkout "${_branch}"
        return 0
    fi

    if git show-ref --verify --quiet "refs/remotes/origin/${_branch}"; then
        git checkout -B "${_branch}" "origin/${_branch}"
        return 0
    fi

    if [[ "${_branch}" =~ ^pr([0-9]+)(-|$) ]]; then
        pr_number="${BASH_REMATCH[1]}"
        if git ls-remote --exit-code origin "refs/pull/${pr_number}/head" >/dev/null 2>&1; then
            git fetch origin "refs/pull/${pr_number}/head:refs/heads/${_branch}"
            git checkout "${_branch}"
            return 0
        fi
    fi

    die ${EC_GIT_ERROR} "ERROR: cannot resolve OPALX branch '${_branch}' in ${PWD}.
Checked local branch '${_branch}', remote branch 'origin/${_branch}'$(
        [[ -n "${pr_number}" ]] && printf ", and GitHub PR ref 'refs/pull/%s/head'" "${pr_number}"
    ).
Use a branch name that exists on origin, or for PR branches use a name like pr501-description only when refs/pull/501/head exists on the OPALX remote."
}

update_repo() {
        # Variables (read-only) to hold the arguments
	local -r _dir="$1"
	local -r _branch="$2"
	local -r _url="$3"

        # Checks if the arguements are non-zero, exit the script if they are
	[[ -n "${_dir}" ]]    || die ${EC_ARG_ERROR} "Oops in $0: no repo dir passed!"
	[[ -n "${_branch}" ]] || die ${EC_ARG_ERROR} "Oops in $0: no branch name passed!"
	[[ -n "${_url}" ]]    || die ${EC_ARG_ERROR} "Oops in $0: no repo URL passed!"

        # Checks if the the directory does not exist, clones
	if [[ ! -d "${_dir}" ]]; then
		git clone "${_url}" "${_dir}"
		cd "${_dir}"
        checkout_requested_ref "${_branch}"
        [[ -x gen_OPALrevision || -f gen_OPALrevision ]] && bash gen_OPALrevision
		return 0
        # Otherwise merge the changes 
	else
		cd "${_dir}"
		git rev-parse --is-inside-work-tree 1>/dev/null 2>&1 || \
			die ${EC_GIT_ERROR} "${_dir}: is not a Git working directory!"
        restore_opalx_source_overrides
        local current_branch
        current_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)
		checkout_requested_ref "${_branch}"

        if ! git show-ref --verify --quiet "refs/remotes/origin/${_branch}"; then
            echo "No remote branch origin/${_branch}; using checked-out local branch '${_branch}'."
            [[ -x gen_OPALrevision || -f gen_OPALrevision ]] && bash gen_OPALrevision
            return 0
        fi

		local -i num_changed_files=$(git diff --name-only  "origin/${_branch}"  | wc -l | awk '{print $1}')
		if (( $num_changed_files == 0 )); then
			echo "Working directory '${_dir}' is up to date!"
            [[ "${current_branch}" != "${_branch}" ]] && return 0
			return 1
		fi
		git merge "origin/${_branch}"
        [[ -x gen_OPALrevision || -f gen_OPALrevision ]] && bash gen_OPALrevision
		return 0
	fi
}

compile_opalx() {
    result_compile='failed'
	rm -rf "${builddir}"
	mkdir -p "${builddir}"
	cd "${builddir}"
	cmake "${cmake_args[@]}" "${srcdir}"
	time make -j8
    result_compile='ok'
    if [[ "${clean_after_compile}" == 'yes' ]]; then
        printf "\nCleaning build object files after successful compile\n"
        cmake --build . --target clean
    fi
}

apply_opalx_source_overrides() {
    local -r patch_file="${bindir}/patches/FieldMirror.hpp"
    local -r target_file="${srcdir}/src/PartBunch/FieldMirror.hpp"

    [[ -f "${patch_file}" ]] || return 1
    [[ -f "${target_file}" ]] || return 1

    if ! cmp -s "${patch_file}" "${target_file}"; then
        cp "${patch_file}" "${target_file}"
        echo "Copied patched FieldMirror.hpp for latest IPPL compatibility."
        return 0
    fi

    return 1
}

check_plot_dependencies() {
    if [[ "${do_no_gpl}" == 'yes' ]]; then
        python3 -c "import matplotlib" >/dev/null 2>&1 || \
            die 1 "ERROR: --no-gpl requires matplotlib, but Python cannot import it."
    else
        command -v gnuplot >/dev/null 2>&1 || \
            die 1 "ERROR: gnuplot is required for regression comparison plots. Use --no-gpl to switch to the Python plotting backend."
    fi
}

run_regressiontests() {
    # Python file to run tests
    local -r run_tests="${bindir}/run-reg-tests.py"

    # Array to hold arguments
    local opts=()

    # Create publishing directory
    if [[ -n "${publish_dir}" ]]; then
        local -r publish_regtests_dir="${publish_dir}/regressionTests/${branch_slug}/${architecture}"
        mkdir -p "${publish_regtests_dir}"
        opts+=("--publish-dir=${publish_regtests_dir}")
    fi

    # Append the OPALX arguments to the array
	if [[ -n "${opalx_args}" ]]; then
		opts+=(${opalx_args[@]/#/--opalx-args=})
	fi
    opts+=("--opalx-exe-path=${opalx_exe_path}")
	opts+=("--base-dir=${testsdir}")
    opts+=("--timestamp=${timestamp}")
    if [[ "${do_no_gpl}" == 'yes' ]]; then
        opts+=("--no-gpl")
    fi
    if [[ "${do_generate_web_page}" == 'yes' ]]; then
        opts+=("--only-generate-web-page")
    fi

    # Run regression tests
    if command -v salloc >/dev/null 2>&1 && sinfo >/dev/null 2>&1; then
        salloc --gpus=1 --partition=gwendolen --cluster=gmerlin6  --account=gwendolen --nodes=1 --ntasks=1 --cpus-per-task=1 --time=02:00:00 srun --pty python3 "${run_tests}" "${opts[@]}" "--" "${tests[@]}"
    else
        python3 "${run_tests}" "${opts[@]}" "--" "${tests[@]}"
    fi

    # Ensure existance of publishing directory
    local -i ec=$?
    [[ -n ${publish_dir} ]] || return ${ec}

    # compile the XML results file with the XSLT stylesheet
    local -r results_xml="${publish_regtests_dir}/results_${timestamp}.xml"
    local -r results_xslt="${publish_regtests_dir}/results.xslt"
    if [[ -f "${results_xml}" && -f "${results_xslt}" ]]; then
        xsltproc "${results_xslt}" "${results_xml}" > "${results_xml%.*}.html"
    fi

    # get results from HTML file created/updated by regression-tests 
    local index_html="${publish_regtests_dir}/index.html"
    if [[ -f "${index_html}" ]]; then
        read passed broken failed total < <(
                awk "/${timestamp}/ {
                        split(\$4, p, \":\");
                        split(\$6, b, \":\");
                        split(\$8, f, \":\");
                        split(\$10, t,  \":\");
                        printf \"%s %s %s %s\n\", p[2], b[2], f[2], t[2]; exit}" \
                                < "${index_html}")
        result_r_total=${total/\]}
        result_r_passed=${passed}
        result_r_failed=${failed}
        result_r_disabled='-'
        result_r_broken=${broken}
    fi

    return ${ec}
}

run_local_now() {
    local -r run_tests="${bindir}/run-reg-tests.py"
    local opts=("--run-local-now")
    opts+=("--timestamp=${timestamp}")
    if [[ "${do_no_gpl}" == 'yes' ]]; then
        opts+=("--no-gpl")
    fi
    if [[ "${do_generate_web_page}" == 'yes' ]]; then
        opts+=("--only-generate-web-page")
    fi

    if [[ -n "${publish_dir}" ]]; then
        opts+=("--publish-dir=${publish_dir}")
    fi

    python3 "${run_tests}" "${opts[@]}"
    local -i ec=$?

    [[ -n "${publish_dir}" ]] || return ${ec}

    local -r results_xml="${publish_dir}/results_${timestamp}.xml"
    local -r results_xslt="${publish_dir}/results.xslt"
    if [[ -f "${results_xml}" && -f "${results_xslt}" ]]; then
        xsltproc "${results_xslt}" "${results_xml}" > "${results_xml%.*}.html"
    fi

    return ${ec}
}

run_unittests() {
    result_u_total='-'
    result_u_passed='-'
    result_u_failed='-'
    result_u_disabled='-'
    result_u_broken='-'

    local results_txt=''
    if [[ -n "${publish_dir}" ]]; then
        local -r unit_dir="${publish_dir}/unitTests/${branch_slug}/${architecture}"
        mkdir -p "${unit_dir}"
        results_txt="${unit_dir}/results_${timestamp}.txt"
    fi

    [[ -d "${builddir}" ]] || return 0
    [[ -f "${builddir}/CTestTestfile.cmake" ]] || return 0

    cd "${builddir}"
    # Run labeled unit tests and capture output; exit code from ctest.
    local -i ec
    if [[ -n "${results_txt}" ]]; then
        ctest -L unit --output-on-failure "${unittests_args[@]}" | tee "${results_txt}"
        ec=${PIPESTATUS[0]}
    else
        ctest -L unit --output-on-failure "${unittests_args[@]}"
        ec=$?
    fi

    # Parse summary line, e.g. "100% tests passed, 0 tests failed out of 10"
    if [[ -n "${results_txt}" && -s "${results_txt}" ]]; then
        local summary
        summary=$(grep -E "tests failed out of" "${results_txt}" | tail -n 1 || true)
        if [[ -n "${summary}" ]]; then
            local failed total
            if [[ "${summary}" =~ ([0-9]+)\ tests\ failed\ out\ of\ ([0-9]+) ]]; then
                failed="${BASH_REMATCH[1]}"
                total="${BASH_REMATCH[2]}"
                result_u_total="${total}"
                result_u_failed="${failed}"
                if [[ -n "${total}" && -n "${failed}" ]]; then
                    result_u_passed="$(( total - failed ))"
                fi
                result_u_disabled='-'
                result_u_broken='-'
            fi
        fi
    fi

    return ${ec}
}

update_overview() {
    # nothing to do if ...
    [[ -n ${publish_dir} ]] || return 0
    [[ "${result_compile}${result_u_total}${result_r_total}" == '---' ]] && return 0

    # Create overview directory - separate from test results
    local -r overview_dir="${publish_dir}/overview/${branch_slug}/${architecture}"
    mkdir -p "${overview_dir}"

    # org file with the table we have to update
    local -r index_org="${overview_dir}/index.org"

    # Always regenerate header from template to ensure placeholders are current
    # First, extract existing table data if the file exists
    local -r tmpfile=$(mktemp "/tmp/index_table.XXXXXX")
    if [[ -e "${index_org}" ]]; then
        # Extract only the table lines (starting from the date header)
        awk '/\|.*Date.*build.*unit-tests.*regression-tests/ {found=1} found {print}' "${index_org}" > "${tmpfile}"
    else
        # New file - create empty table
        echo '|       Date | build | unit-tests   | regression-tests   |' > "${tmpfile}"
        echo '|------------+-------+--------------+--------------------|' >> "${tmpfile}"
        echo '|            |       |              |                    |' >> "${tmpfile}"
    fi

    # Regenerate the full file from template with substitutions
    local branch_escaped architecture_escaped
    branch_escaped=$(escape_sed_replacement "${branch}")
    architecture_escaped=$(escape_sed_replacement "${architecture}")
    sed -e "s/@BRANCH@/${branch_escaped}/g" \
        -e "s/@ARCHITECTURE@/${architecture_escaped}/g" \
        "${bindir}/html/index.org" > "${index_org}"
    
    # Remove the template's empty table and append the actual table data
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' '/|.*Date.*build.*unit-tests.*regression-tests/,$ d' "${index_org}"
    else
        sed -i '/|.*Date.*build.*unit-tests.*regression-tests/,$ d' "${index_org}"
    fi
    cat "${tmpfile}" >> "${index_org}"
    rm -f "${tmpfile}"

    # links to generated XML pages used in the table
    # Adjusted relative paths from overview directory
    local -r u_results_html="../../../unitTests/${branch_slug}/${architecture}/results_${timestamp}.txt"
    local -r r_results_html="../../../regressionTests/${branch_slug}/${architecture}/results_${timestamp}.html"

    local time_col
    local ofile="${publish_dir}/output/${branch_slug}/${architecture}/${timestamp}.txt"
    if [[ -e "${ofile}" ]]; then
        time_col="[[../../../output/${branch_slug}/${architecture}/${timestamp}.txt][${today} ${time/-/:}]]"
    else
        time_col="${today} ${time/-/:}"
    fi

    # build string with result for unit-tests. This will be used as link-name.
    if [[ "${result_u_total}" == "-" ]]; then
        local -r u_report='-'
    else
        local -r u_t="total:${result_u_total}"
        local -r u_p="passed:${result_u_passed}"
        local -r u_f="failed:${result_u_failed}"
        local -r u_d="disabled:${result_u_disabled}"
        local -r u_b="broken:${result_u_broken}"
        local -r u_report="[[${u_results_html}][${u_t}; ${u_p}; ${u_f}; ${u_d}; ${u_b}]]"
    fi
    # build string with result for regression-tests. This will be used as link-name.
    if [[ "${result_r_total}" == "-" ]]; then
        local -r r_report='-'
    else
        local -r r_t="total:${result_r_total}"
        local -r r_p="passed:${result_r_passed}"
        local -r r_f="failed:${result_r_failed}"
        local -r r_d="disabled:${result_r_disabled}"
        local -r r_b="broken:${result_r_broken}"
        local -r r_report="[[${r_results_html}][${r_t}, ${r_p}, ${r_f}, ${r_d}, ${r_b}]]"
    fi
    # add new line to org table
    line=""
    line+="| ${time_col} "
    line+="| ${result_compile} "
    line+="| ${u_report} "
    line+="| ${r_report} "
    line+="|"
    awk "{print}; /^\|-/ {print \"${line}\"}" \
        "${index_org}" > "${tmpfile}"
    mv "${tmpfile}" "${index_org}"

    # Remove #+SETUPFILE if present to avoid file read errors on local builds
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' '/^#+SETUPFILE/d' "${index_org}"
    else
        sed -i '/^#+SETUPFILE/d' "${index_org}"
    fi

    # Define the styles to embed
    local -r style_content="<style>
  $(cat ${bindir}/html/org-html-themes/src/readtheorg_theme/css/htmlize.css 2>/dev/null || echo '')
  $(cat ${bindir}/html/org-html-themes/src/readtheorg_theme/css/readtheorg.css 2>/dev/null || echo '')
</style>
<script type=\"text/javascript\">
  $(cat ${bindir}/html/org-html-themes/src/readtheorg_theme/js/readtheorg.js 2>/dev/null || echo '')
</script>"

    pandoc -f org -t html \
        --metadata title="OPALX" \
        --include-in-header=<(echo "${style_content}") \
        -s -o "${index_org%.*}.html" "${index_org}"
    
    # Update master landing page with all architectures
    update_master_landing_page
    update_branch_selector_page
    overview_dirty='no'
}

update_master_landing_page() {
    # Master landing page location
    local -r master_dir="${publish_dir}/overview/${branch_slug}"
    local -r master_org="${master_dir}/index.org"
    local -r master_html="${master_dir}/index.html"
    
    mkdir -p "${master_dir}"
    printf "%s\n" "${branch}" > "${master_dir}/branch-name.txt"
    
    # Find all architecture directories under this branch
    local -a architectures=()
    if [[ -d "${publish_dir}/overview/${branch_slug}" ]]; then
        while IFS= read -r arch_dir; do
            local arch_name=$(basename "${arch_dir}")
            # Skip files, only process directories
            [[ -d "${arch_dir}" ]] && [[ -f "${arch_dir}/index.html" ]] && architectures+=("${arch_name}")
        done < <(find "${publish_dir}/overview/${branch_slug}" -maxdepth 1 -type d ! -path "${publish_dir}/overview/${branch_slug}")
    fi
    
    # Build the master page from template
    local -r tmpfile=$(mktemp "/tmp/master-landing.XXXXXX")
    local branch_escaped
    branch_escaped=$(escape_sed_replacement "${branch}")
    
    # Copy template and substitute @BRANCH@, stop at placeholder
    sed "s/@BRANCH@/${branch_escaped}/g" "${bindir}/html/master-index.org" | \
        awk '/ARCHITECTURE_LINKS will be inserted here/ {exit} {print}' > "${tmpfile}"
    
    # Add links for each architecture
    if (( ${#architectures[@]} > 0 )); then
        for arch in "${architectures[@]}"; do
            echo "" >> "${tmpfile}"
            echo "- [[./${arch}/index.html][${arch} Details]]" >> "${tmpfile}"
        done
    else
        echo "" >> "${tmpfile}"
        echo "No architectures available yet. Run tests to populate this page." >> "${tmpfile}"
    fi
    
    # Write the updated master page
    mv "${tmpfile}" "${master_org}"
    
    # Remove #+SETUPFILE if present to avoid file read errors on local builds
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' '/^#+SETUPFILE/d' "${master_org}"
    else
        sed -i '/^#+SETUPFILE/d' "${master_org}"
    fi
    
    # Convert to HTML
    local -r style_content="<style>
  $(cat ${bindir}/html/org-html-themes/src/readtheorg_theme/css/htmlize.css 2>/dev/null || echo '')
  $(cat ${bindir}/html/org-html-themes/src/readtheorg_theme/css/readtheorg.css 2>/dev/null || echo '')
</style>
<script type=\"text/javascript\">
  $(cat ${bindir}/html/org-html-themes/src/readtheorg_theme/js/readtheorg.js 2>/dev/null || echo '')
</script>"
    
    pandoc -f org -t html \
        --metadata title="OPALX Regression Tests" \
        --include-in-header=<(echo "${style_content}") \
        -s -o "${master_html}" "${master_org}"
}

trim_text() {
    local value="$1"
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"
    printf "%s" "${value}"
}

latest_overview_row() {
    local -r index_org="$1"
    [[ -f "${index_org}" ]] || return 1
    awk '/^\| [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/ {print; exit}' "${index_org}"
}

test_status_class() {
    local report="$1"
    report=$(trim_text "${report}")

    if [[ -z "${report}" || "${report}" == "-" ]]; then
        printf "skip"
    elif [[ "${report}" == *"failed:0"* && ( "${report}" == *"broken:0"* || "${report}" == *"broken:-"* ) ]]; then
        printf "ok"
    else
        printf "nok"
    fi
}

test_status_label() {
    local -r status_value="$1"
    case "${status_value}" in
        ok) printf "ok" ;;
        nok) printf "nok" ;;
        *) printf "-" ;;
    esac
}

branch_architecture_checks_html() {
    local -r overview_dir="$1"
    local -r branch_name="$2"
    local -a arch_dirs=()
    local arch_dir arch_name index_org row
    local _ date_col build_col unit_col regression_col __
    local unit_status regression_status unit_label regression_label

    while IFS= read -r arch_dir; do
        [[ -f "${arch_dir}/index.org" ]] && arch_dirs+=( "${arch_dir}" )
    done < <(find "${overview_dir}/${branch_name}" -maxdepth 1 -type d ! -path "${overview_dir}/${branch_name}" | sort)

    for arch_dir in "${arch_dirs[@]}"; do
        arch_name=$(basename "${arch_dir}")
        index_org="${arch_dir}/index.org"
        row=$(latest_overview_row "${index_org}" || true)

        if [[ -n "${row}" ]]; then
            IFS='|' read -r _ date_col build_col unit_col regression_col __ <<< "${row}"
            unit_status=$(test_status_class "${unit_col}")
            regression_status=$(test_status_class "${regression_col}")
        else
            date_col="-"
            unit_status="skip"
            regression_status="skip"
        fi

        unit_label=$(test_status_label "${unit_status}")
        regression_label=$(test_status_label "${regression_status}")
        date_col=$(trim_text "${date_col}")

        printf '        <div class="arch-line"><a href="%s/%s/index.html">%s</a><span class="badge %s"><span class="dot"></span>Unit %s</span><span class="badge %s"><span class="dot"></span>Reg %s</span><span class="run-date">%s</span></div>\n' \
            "${branch_name}" "${arch_name}" "${arch_name}" \
            "${unit_status}" "${unit_label}" \
            "${regression_status}" "${regression_label}" \
            "${date_col}"
    done
}

update_branch_selector_page() {
    [[ -n "${publish_dir}" ]] || return 0

    local -r overview_dir="${publish_dir}/overview"
    local -r selector_html="${overview_dir}/index.html"
    mkdir -p "${overview_dir}"

    local -a branch_dirs=()
    while IFS= read -r branch_dir; do
        [[ -f "${branch_dir}/index.html" ]] && branch_dirs+=( "$(basename "${branch_dir}")" )
    done < <(find "${overview_dir}" -maxdepth 1 -type d ! -path "${overview_dir}" | sort)

    {
        printf '%s\n' \
            '<!doctype html>' \
            '<html lang="en">' \
            '<head>' \
            '  <meta charset="utf-8">' \
            '  <title>OPALX Regression Test Branches</title>' \
            '  <style>' \
            '    body { font-family: system-ui, sans-serif; margin: 2rem; color: #20242a; }' \
            '    main { max-width: 72rem; }' \
            '    h1 { margin-top: 0; border-bottom: 3px solid #2c5aa0; padding-bottom: 0.5rem; }' \
            '    label { display: block; font-weight: 600; margin: 1.5rem 0 0.4rem; }' \
            '    select { min-width: 18rem; padding: 0.45rem; font: inherit; }' \
            '    table { border-collapse: collapse; width: 100%; margin-top: 1.5rem; }' \
            '    th, td { border-bottom: 1px solid #d8dde5; padding: 0.55rem; text-align: left; }' \
            '    a { color: #1d4f91; }' \
            '    .branch { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }' \
            '    .arch-checks { margin-top: 0.45rem; display: grid; gap: 0.35rem; }' \
            '    .arch-line { display: flex; flex-wrap: wrap; align-items: center; gap: 0.45rem; }' \
            '    .badge { display: inline-flex; align-items: center; gap: 0.25rem; border: 1px solid #ccd3dd; border-radius: 0.25rem; padding: 0.12rem 0.35rem; font-size: 0.82rem; }' \
            '    .dot { width: 0.65rem; height: 0.65rem; border-radius: 50%; display: inline-block; background: #9aa3af; }' \
            '    .ok .dot { background: #15803d; }' \
            '    .nok .dot { background: #b91c1c; }' \
            '    .skip .dot { background: #9aa3af; }' \
            '    .run-date { color: #667085; font-size: 0.82rem; }' \
            '  </style>' \
            '</head>' \
            '<body>' \
            '<main>' \
            '  <h1>OPALX Regression Test Branches</h1>' \
            '  <label for="branchSelect">Branch</label>' \
            '  <select id="branchSelect" onchange="if (this.value) window.location.href = this.value;">' \
            '    <option value="">Select a branch...</option>'
        local branch_name branch_label label_file
        for branch_name in "${branch_dirs[@]}"; do
            label_file="${overview_dir}/${branch_name}/branch-name.txt"
            branch_label="${branch_name}"
            [[ -f "${label_file}" ]] && branch_label=$(<"${label_file}")
            printf '    <option value="%s/index.html">%s</option>\n' "${branch_name}" "${branch_label}"
        done
        printf '%s\n' \
            '  </select>' \
            '  <table>' \
            '    <thead><tr><th>Branch</th><th>Results</th></tr></thead>' \
            '    <tbody>'
        for branch_name in "${branch_dirs[@]}"; do
            label_file="${overview_dir}/${branch_name}/branch-name.txt"
            branch_label="${branch_name}"
            [[ -f "${label_file}" ]] && branch_label=$(<"${label_file}")
            printf '      <tr><td class="branch">%s</td><td><a href="%s/index.html">Open results</a><div class="arch-checks">\n' "${branch_label}" "${branch_name}"
            branch_architecture_checks_html "${overview_dir}" "${branch_name}"
            printf '      </div></td></tr>\n'
        done
        printf '%s\n' \
            '    </tbody>' \
            '  </table>' \
            '</main>' \
            '</body>' \
            '</html>'
    } > "${selector_html}"
}

run_current_branch() {
    set_branch_context
    reset_results

    printf "\n== OPALX branch: %s ==\n" "${branch}"

    if [[ "${do_run_local_now}" == 'yes' || \
          "${do_regtests}" == 'yes' || \
          "${do_generate_web_page}" == 'yes' || \
          "${opt_force}" == 'yes' ]]; then
        check_plot_dependencies
    fi

    if [[ "${do_run_local_now}" == 'yes' || \
          ( "${do_generate_web_page}" == 'yes' && \
            "${do_compile}" == 'no' && \
            "${do_unittests}" == 'no' && \
            "${do_regtests}" == 'no' && \
            "${opt_force}" == 'no' ) ]]; then
        run_local_now
        return $?
    fi

    if [[ -n "${opt_opalx_build_dir}" ]]; then
        managed_build_layout='no'
        builddir=$(python3 -c "import os, sys; print(os.path.abspath(sys.argv[1]))" "${opt_opalx_build_dir}")
        if [[ -z "${opt_opalx_exe_path}" ]]; then
            opt_opalx_exe_path="${builddir}/src"
        fi
    fi

    if [[ -n "${opt_opalx_exe_path}" ]]; then
        opalx_exe_path=$(python3 -c "import os, sys; print(os.path.abspath(sys.argv[1]))" "${opt_opalx_exe_path}")
        if [[ ! -x "${opalx_exe_path}/opalx" ]]; then
            die 1 "ERROR: --opalx-exe-path must point to a directory containing an executable opalx - ${opalx_exe_path}"
        fi
        do_compile='no'
        if [[ "${explicit_actions}" == 'no' ]]; then
            do_regtests='yes'
        fi
        result_compile='external'
        printf "\nUsing existing OPALX executable: ${opalx_exe_path}/opalx\n"
        if [[ -n "${opt_opalx_build_dir}" ]]; then
            printf "Using existing OPALX build directory: ${builddir}\n"
        fi
    fi

    # local variable for the opalx binary
    local -r opalxbin="${opalx_exe_path}/opalx"

    if [[ -z "${opt_opalx_exe_path}" ]]; then
    
        # Getting latest repo version
        printf "\nUpdating OPALX source repository... \n"
	    if update_repo "${srcdir}" "${branch}" "${src_repo_url}"; then
            do_compile='yes'
        fi
        apply_opalx_source_overrides && do_compile='yes' || true

        # If the binary does not exist we need to compile
        [[ -e ${opalxbin} ]] || do_compile='yes'
    fi
	aborting='no'
    overview_dirty='yes'
 
    # Compilation
	if [[ "${do_compile}" == "yes" ]]; then
        printf "\nStarting OPALX compilation \n"
		compile_opalx
        if [[ "${explicit_actions}" == 'no' ]]; then
		    do_unittests='yes'
		    do_regtests='yes'
        fi
	fi
    
    # Unit tests
    if [[ ${do_unittests} == 'yes' ]]; then
        printf "\nRunning unit tests (ctest -L unit)\n"
        run_unittests || true
    fi

    # Regression test
    if [[ "${do_regtests}" == 'yes' || "${explicit_actions}" == 'no' ]]; then
        printf "\nUpdating regression tests repository...\n"
	    update_repo "${testsbase}" "${regtests_branch}" "${tests_repo_url}" && do_regtests='yes'
    fi

    if [[ ${do_regtests} == 'yes' ]]; then
        printf "\nRunning regression tests for OPALX\n"
        run_regressiontests || return 1
    fi

    update_overview
}

main() {
    local -a branches=()
    local default_branches_file="${HOME}/branches.txt"
    if [[ "${opt_branches_file_set}" == 'yes' ]]; then
        read_branches_file "${opt_branches_file}"
    elif [[ -z "${opt_opalx_branch}" && -f "${default_branches_file}" ]]; then
        read_branches_file "${default_branches_file}"
    else
        branches=( "${branch}" )
    fi

    local initial_do_compile="${do_compile}"
    local initial_do_unittests="${do_unittests}"
    local initial_do_regtests="${do_regtests}"
    local initial_managed_build_layout="${managed_build_layout}"

    local selected_branch
    for selected_branch in "${branches[@]}"; do
        branch="${selected_branch}"
        do_compile="${initial_do_compile}"
        do_unittests="${initial_do_unittests}"
        do_regtests="${initial_do_regtests}"
        managed_build_layout="${initial_managed_build_layout}"
        run_current_branch
    done
}

main
